### ISSUE TITLE
Click on searchbar it was crashing

### ISSUE THREAD

**Issue by Pedasingu-Vijay-Krishna** [fluttercommunity/flutter_google_places#103]
in some devices  clicking on seachbar it was going to appcrash

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
