### ISSUE TITLE
How to get the data from the search bar and display it in text?

### ISSUE THREAD

**Issue by Aishwarya1317** [fluttercommunity/flutter_google_places#107]

**Comment by abhijithvijayan** [comment]
@Aishwarya1317 Is this a bug or something, I can't seem to show the search output place name in the TextInput?

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
