### ISSUE TITLE
status = INVALID_REQUEST

### ISSUE THREAD

**Issue by tneagu** [fluttercommunity/flutter_google_places#124]
The widget used to work, but today started to show 0 results and no error message on the onError callback. 

I put a breakpoint in widget code, and in flutter_google_places.dart, in `Future<Null> doSearch(String value)`, in this block of code

`if (res.errorMessage?.isNotEmpty == true ||
          res.status == "REQUEST_DENIED") {
        onResponseError(res);
      } `

res.status is res.status = INVALID_REQUEST. 

My api key is valid and I did not consumed my quota.

**Comment by KumarSunil17** [comment]
Make sure you have set strictbounds to false.

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
