### ISSUE TITLE
This IP, site or mobile application is not authorized to use this API key.

### ISSUE THREAD

**Issue by charleshan** [fluttercommunity/flutter_google_places#127]
```
This IP, site or mobile application is not authorized to use this API key. Request received from IP address x.x.x.x, with empty referer
```
It looks like this library doesn't let us use app restricted API keys.

Here is the solution: https://github.com/humazed/google_map_location_picker/issues/31

**Comment by zeshuaro** [comment]
I've made a PR (https://github.com/lejard-h/google_maps_webservice/pull/88) on `google_maps_webservice`, which is used by this plugin for making the Google API calls, to support app restricted API keys. Once it's merged and updated, this plugin can also support app restricted API keys.

In the mean time, feel free to use my branch which contains all these changes.
```yml
dependencies:
  flutter_google_places:
    git:
      url: https://github.com/zeshuaro/flutter_google_places.git
      ref: feature/restricted-api-keys
```
