### ISSUE TITLE
Conflict issue with other package....

### ISSUE THREAD

**Issue by rmControls** [fluttercommunity/flutter_google_places#142]
I tried to install flutter_google_places in my app and get below error...

```
Because camerawesome >=0.2.0 depends on rxdart ^0.25.0 and flutter_google_places >=0.2.5 depends on rxdart ^0.24.0, camerawesome >=0.2.0 is incompatible with flutter_google_places >=0.2.5.
So, because myapp_flutter depends on both flutter_google_places ^0.2.6 and camerawesome ^0.2.1, version solving failed.
pub get failed (1; So, because esuggi_flutter depends on both flutter_google_places ^0.2.6 and camerawesome ^0.2.1, version solving failed.)
```

seems like rxdart package dependency needs to be updated....

**Comment by hoc081098** [comment]
Please try my fork: https://github.com/hoc081098/flutter_google_places
```yaml
flutter_google_places:
  git:
    url: https://github.com/hoc081098/flutter_google_places.git
    ref: feature/restricted-api-keys
```
