### ISSUE TITLE
Please upgrade to null safety for latest flutter: 2.0.0

### ISSUE THREAD

**Issue by gouthamravella** [fluttercommunity/flutter_google_places#149]
Also please upgrade the rxdart ^0.21.0 in the package. Which is failing with the dependency package cached_network_image: >=3.0.0-nullsafety

**Comment by jonasbark** [comment]
I'd actually prefer it would remove the cross dependency to rxdart altogether

**Comment by gianlucainnocente** [comment]
We need the rxdart dependency upgraded

**Comment by hoc081098** [comment]
Workaround:
```yaml
dependency_overrides:
  flutter_google_places:
    git:
      url: https://github.com/hoc081098/flutter_google_places.git
      ref: 0566867ee2abe5c8c2ba180678f18309845b23a6
```
