### ISSUE TITLE
Method 'cancel' cannot be called on 'Timer?' because it is potentially null

### ISSUE THREAD

**Issue by BaptisteCool** [fluttercommunity/flutter_google_places#180]
I have this error since i upgrated dart and flutter to last version.

lib/src/flutter_google_places.dart:468:17: Error: Method 'cancel' cannot be called on 'Timer?' because it is potentially null.
 - 'Timer' is from 'dart:async'.
Try calling using ?. instead.
      _debounce.cancel();
                ^^^^^^
/C:/Users/[User]/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_google_places-0.3.0/lib/src/flutter_google_places.dart:392:10: Context: '_debounce' refers to a property so it couldn't be promoted.
See http://dart.dev/go/non-promo-property

  Timer? _debounce;
         ^

do you know the problem ?

**Comment by PascalOtto** [comment]
bug was fixed in #181 

just needs to be pushed to pub.dev

**Comment by juliansteenbakker** [comment]
Please see https://github.com/fluttercommunity/flutter_google_places/issues/182. Until this is fixed i can't publish it.

**Comment by juliansteenbakker** [comment]
Please use this for now:
```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
