### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by NetFreaker** [fluttercommunity/flutter_google_places#186]
Running "flutter pub get" in MobileApp...                     
Because flutterapp depends on flutter_google_places ^0.3.0 which depends on rxdart ^0.26.0, rxdart ^0.26.0 is required.
So, because flutterapp depends on rxdart ^0.27.3, version solving failed.
pub get failed (1; So, because flutterapp depends on rxdart ^0.27.3, version solving failed.)
exit code 1

**Comment by oandreyev-uniper** [comment]
As a variant you can download the plugin from git
```
flutter_google_places:
    git:
      url: git@github.com:fluttercommunity/flutter_google_places.git
      ref: master

```
