### ISSUE TITLE
error thrown when dialog back button is pressed without entering any text into search bar

### ISSUE THREAD

**Issue by Omar-Salem** [fluttercommunity/flutter_google_places#191]
Null check operator used on a null value

**Comment by ziagit** [comment]
please fix this issue

**Comment by juliansteenbakker** [comment]
Can you please try the following in `pubspec.yaml`
```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
