### ISSUE TITLE
cant build apk

### ISSUE THREAD

**Issue by followthemoney1** [fluttercommunity/flutter_google_places#41]
when i try build apk with console i have an error:
```MacBook-Pro-Dmitry:rarare dmitrydyachenko$ flutter build apk
Initializing gradle...                                       2.6s
Resolving dependencies...                                   11.2s
Gradle task 'assembleRelease'...                                 

Compiler message:
file:///Users/dmitrydyachenko/Desktop/rarare_flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_places_autocomplete-0.1.3/lib/src/flutter_google_places_autocomplete.dart:337:35: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    _places = new GoogleMapsPlaces(widget.apiKey);
                                  ^
file:///Users/dmitrydyachenko/Desktop/rarare_flutter/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_webservice-0.0.11/lib/src/places.dart:20:3: Context: Found this candidate, but the arguments don't match.
  GoogleMapsPlaces({
  ^
Compiler terminated unexpectedly.
 
Gradle task 'assembleRelease'... Done                        9.2s
Gradle task assembleRelease failed with exit code 1
```

and my pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: 8.0.0
  http: "^0.11.3+16"
  flutter_google_places_autocomplete: ^0.1.3
  #google_maps_webservice: "^0.0.4"
  location: "^1.2.0"
  flutter_map: ^0.1.0
  dio: ^1.0.6
  flutter_facebook_login: "^1.1.1"
  shared_preferences: "^0.4.2"
  cupertino_icons: ^0.1.0
  image_picker: "^0.4.5"
  intl: ^0.15.7
  progress_hud: ^1.1.0
  json_annotation: ^2.0.0


dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
```
