### ISSUE TITLE
administrativeArea 1 and 2 doesnt work

### ISSUE THREAD

**Issue by SimonHeimer** [fluttercommunity/flutter_google_places#74]
Administrative area doesn't work.   It would be nice to be able to choose between administrativeArea1 and 2 as well!

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
